# Generated by Django 2.2 on 2020-11-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL')),
                ('ean', models.IntegerField(null=True, unique=True, verbose_name='EAN')),
                ('brand', models.CharField(max_length=140, verbose_name='Brand')),
                ('tipe', models.CharField(max_length=140, verbose_name='Tipe')),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('out_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
