# Generated by Django 2.2 on 2020-11-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0004_stockout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockOut',
        ),
    ]
