# Generated by Django 2.2 on 2020-11-03 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0005_delete_stockout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL Tipe')),
                ('ean', models.CharField(max_length=64, unique=True, verbose_name='EAN')),
                ('tipe', models.CharField(max_length=64, unique=True, verbose_name='Nama Tipe')),
                ('brand', models.ForeignKey(default=999, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory_data.Brand', verbose_name='Nama Brand')),
            ],
            options={
                'verbose_name_plural': 'Tipe',
            },
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='slug',
        ),
        migrations.AlterField(
            model_name='stockin',
            name='tipe',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory_data.Tipe', verbose_name='Nama Brand'),
        ),
    ]
