# Generated by Django 2.2 on 2020-11-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0007_auto_20201103_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL Out'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='tipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory_data.Tipe', verbose_name='Nama Tipe'),
        ),
    ]
