# Generated by Django 2.2 on 2020-11-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0008_auto_20201103_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='brand',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory_data.Brand', verbose_name='Nama Brand'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='ean',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='EAN'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL Tipe'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='tipe',
            field=models.CharField(max_length=64, unique=True, verbose_name='Nama Tipe'),
        ),
        migrations.DeleteModel(
            name='Tipe',
        ),
    ]
