# Generated by Django 2.2 on 2020-11-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0010_auto_20201103_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='slug_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slug_out', to='inventory_data.StockIn', verbose_name='URL Barang Keluar'),
        ),
    ]
