# Generated by Django 2.2 on 2020-11-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0011_stockout_slug_out'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockout',
            options={'verbose_name_plural': 'Barang Keluar'},
        ),
        migrations.RenameField(
            model_name='stockout',
            old_name='slug_out',
            new_name='stock_out',
        ),
        migrations.AddField(
            model_name='stockout',
            name='qty_out',
            field=models.PositiveIntegerField(default=1, verbose_name='Jumlah Keluar'),
        ),
    ]
