# Generated by Django 2.2 on 2020-11-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0012_auto_20201103_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL Tipe')),
                ('ean', models.CharField(max_length=64, null=True, unique=True, verbose_name='EAN')),
                ('tipe', models.CharField(max_length=64, unique=True, verbose_name='Nama Tipe')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_data.Brand', verbose_name='Nama Brand')),
            ],
            options={
                'verbose_name_plural': 'Nama Barang',
            },
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='date_in',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='tipe',
        ),
        migrations.AlterField(
            model_name='stockout',
            name='stock_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_data.Tipe', verbose_name='Barang Keluar'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='stock_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_data.Tipe', verbose_name='Barang Masuk'),
        ),
    ]
