# Generated by Django 2.2 on 2020-11-03 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0013_auto_20201103_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='date_in',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
