# Generated by Django 2.2 on 2020-11-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0014_stockin_date_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='suplier',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Supplier'),
        ),
    ]
