# Generated by Django 2.2 on 2020-11-03 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0015_stockin_suplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='date_in',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='pembeli',
            field=models.CharField(max_length=140, null=True, unique=True, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='suplier',
            field=models.CharField(max_length=140, null=True, unique=True, verbose_name='Supplier'),
        ),
    ]
