# Generated by Django 2.2 on 2020-11-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0016_auto_20201103_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockout',
            name='pembeli',
        ),
        migrations.AddField(
            model_name='stockout',
            name='buyer',
            field=models.CharField(max_length=140, null=True, unique=True, verbose_name='Buyer'),
        ),
        migrations.AddField(
            model_name='tipe',
            name='qty_total',
            field=models.PositiveIntegerField(default=1, verbose_name='Jumlah Masuk'),
        ),
    ]
