# Generated by Django 2.2 on 2020-11-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0017_auto_20201103_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipe',
            name='qty_total',
        ),
        migrations.CreateModel(
            name='StockTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_data.Tipe', verbose_name='Nama Barang')),
                ('total_qty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_data.StockIn', verbose_name='Stock Total')),
            ],
        ),
    ]
