# Generated by Django 2.2 on 2020-11-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0019_auto_20201103_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipe',
            name='qty_total',
        ),
    ]
