# Generated by Django 2.2 on 2020-11-03 15:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0020_remove_tipe_qty_total'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tipe',
            managers=[
                ('qty', django.db.models.manager.Manager()),
            ],
        ),
    ]
