# Generated by Django 2.2 on 2020-11-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0021_auto_20201103_1558'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tipe',
            managers=[
            ],
        ),
    ]
