# Generated by Django 2.2 on 2020-11-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0022_auto_20201103_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipe',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
    ]
