# Generated by Django 2.2 on 2020-11-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0024_auto_20201103_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedstock',
            name='qty_in',
        ),
    ]
