# Generated by Django 2.2 on 2020-11-04 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0025_remove_receivedstock_qty_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellout',
            name='tipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_data.ReceivedStock', verbose_name='Tipe Barang'),
        ),
    ]
