# Generated by Django 2.2 on 2020-11-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0026_auto_20201104_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellout',
            name='admin_pass',
            field=models.CharField(max_length=140, null=True, unique=True, verbose_name='Invoice'),
        ),
    ]
