# Generated by Django 2.2 on 2020-11-04 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0027_sellout_admin_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL Stock')),
                ('tipe', models.CharField(max_length=140, null=True, unique=True, verbose_name='Tipe Barang')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_data.Brand', verbose_name='Nama Brand')),
            ],
            options={
                'verbose_name_plural': 'Tipe',
            },
        ),
        migrations.AddField(
            model_name='receivedstock',
            name='quantity',
            field=models.CharField(max_length=140, null=True, unique=True, verbose_name='Jumlah Barang'),
        ),
        migrations.AlterField(
            model_name='receivedstock',
            name='tipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_data.Tipe', verbose_name='Nama Tipe'),
        ),
    ]
