# Generated by Django 2.2 on 2020-11-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0028_auto_20201104_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedstock',
            name='admin_pass',
            field=models.CharField(max_length=140, null=True, unique=True, verbose_name='Invoice'),
        ),
    ]
