# Generated by Django 2.2 on 2020-11-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0030_auto_20201104_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipe',
            name='ean',
            field=models.CharField(max_length=140, null=True, unique=True, verbose_name='Tipe Barang'),
        ),
    ]
