# Generated by Django 2.2 on 2020-11-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0031_tipe_ean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivedstock',
            old_name='admin_pass',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='sellout',
            old_name='admin_pass',
            new_name='invoice',
        ),
        migrations.AlterField(
            model_name='tipe',
            name='ean',
            field=models.CharField(max_length=140, null=True, unique=True, verbose_name='EAN Barang'),
        ),
    ]
