# Generated by Django 2.2 on 2020-11-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0032_auto_20201104_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipe',
            name='quantity_all',
            field=models.PositiveIntegerField(default=1, verbose_name='Jumlah Total'),
        ),
        migrations.AlterField(
            model_name='receivedstock',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Jumlah Masuk'),
        ),
    ]
