# Generated by Django 2.2 on 2020-11-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0033_auto_20201104_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivedstock',
            old_name='tipe',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sellout',
            old_name='tipe',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='tipe',
            old_name='tipe',
            new_name='product',
        ),
    ]
