# Generated by Django 2.2 on 2020-11-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0034_auto_20201104_0526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivedstock',
            old_name='quantity',
            new_name='quantity_in',
        ),
        migrations.RenameField(
            model_name='sellout',
            old_name='sell_qty',
            new_name='sell_quantity',
        ),
    ]
