# Generated by Django 2.2 on 2020-11-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0036_auto_20201104_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipe',
            name='quantity_received',
            field=models.PositiveIntegerField(default=1, verbose_name='Jumlah Total'),
        ),
        migrations.AddField(
            model_name='tipe',
            name='quantity_sell_out',
            field=models.PositiveIntegerField(default=1, verbose_name='Jumlah Total'),
        ),
        migrations.AlterField(
            model_name='receivedstock',
            name='invoice',
            field=models.CharField(max_length=140, null=True, unique=True, verbose_name='Invoice Masuk'),
        ),
        migrations.AlterField(
            model_name='sellout',
            name='invoice',
            field=models.CharField(max_length=140, null=True, unique=True, verbose_name='Invoice Jual'),
        ),
    ]
