# Generated by Django 2.2 on 2020-11-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0037_auto_20201104_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipe',
            name='quantity_all',
        ),
        migrations.RemoveField(
            model_name='tipe',
            name='quantity_received',
        ),
        migrations.RemoveField(
            model_name='tipe',
            name='quantity_sell_out',
        ),
    ]
