# Generated by Django 2.2 on 2020-11-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0038_auto_20201104_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipe',
            name='quantity_in',
            field=models.PositiveIntegerField(default=1, verbose_name='Jumlah Masuk'),
        ),
        migrations.AddField(
            model_name='tipe',
            name='quantity_out',
            field=models.PositiveIntegerField(default=1, verbose_name='Jumlah Masuk'),
        ),
    ]
