# Generated by Django 2.2 on 2020-11-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0041_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'Stock'},
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='category',
            new_name='brand',
        ),
    ]
