# Generated by Django 2.2 on 2020-11-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0043_auto_20201104_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ean',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Product ID'),
        ),
    ]
