# Generated by Django 2.2 on 2020-11-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0045_auto_20201104_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64, verbose_name='Nama Brand')),
            ],
            options={
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_data.Brand', verbose_name='Nama Brand'),
        ),
    ]
