# Generated by Django 2.2 on 2020-11-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0046_auto_20201104_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
