# Generated by Django 2.2 on 2020-11-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0048_remove_stock_export_to_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
