# Generated by Django 2.2 on 2020-11-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0049_stock_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
