# Generated by Django 2.2 on 2020-11-05 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0051_stockhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
