# Generated by Django 2.2 on 2020-11-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0053_historicalstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL Product')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand')),
                ('ean', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Product ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Name')),
                ('quantity', models.IntegerField(blank=True, default='0', null=True, verbose_name='Total Quantity')),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True, verbose_name='Received Quantity')),
                ('receive_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Warehouse Admin')),
                ('supplier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplier')),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True, verbose_name='Sell Out Quantity')),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Warehouse Admin')),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buyer')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('date_added', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'Stock Store A'},
        ),
        migrations.DeleteModel(
            name='HistoricalStock',
        ),
    ]
