# Generated by Django 2.2 on 2020-11-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0054_auto_20201107_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
