# Generated by Django 2.2 on 2020-11-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0056_auto_20201107_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='ean',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product ID'),
        ),
    ]
