# Generated by Django 2.2 on 2020-11-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0057_auto_20201107_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'verbose_name_plural': 'Stock History Store A'},
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='created_by',
        ),
    ]
