# Generated by Django 2.2 on 2020-11-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0058_auto_20201107_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='created_by',
        ),
    ]
