# Generated by Django 2.2 on 2020-11-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data', '0060_auto_20201109_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='issue_invoice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Invoice Sell Out'),
        ),
    ]
