# Generated by Django 2.2 on 2020-11-05 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStoreB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL Product')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand')),
                ('ean', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Product ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Name')),
                ('quantity', models.IntegerField(blank=True, default='0', null=True, verbose_name='Total Quantity')),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True, verbose_name='Received Quantity')),
                ('receive_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Warehouse Admin')),
                ('supplier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplier')),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True, verbose_name='Sell Out Quantity')),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Warehouse Admin')),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buyer')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='HistoricalStockStoreB',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('slug', models.SlugField(null=True, verbose_name='URL Product')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand')),
                ('ean', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Product ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Name')),
                ('quantity', models.IntegerField(blank=True, default='0', null=True, verbose_name='Total Quantity')),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True, verbose_name='Received Quantity')),
                ('receive_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Warehouse Admin')),
                ('supplier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplier')),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True, verbose_name='Sell Out Quantity')),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Warehouse Admin')),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buyer')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('date_added', models.DateTimeField(blank=True, editable=False)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical stock store b',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
