# Generated by Django 2.2 on 2020-11-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data_store_b', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalStockStoreB',
        ),
    ]
