# Generated by Django 2.2 on 2020-11-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_data_store_b', '0002_delete_historicalstockstoreb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockstoreb',
            options={'verbose_name_plural': 'Stock Store B'},
        ),
    ]
